### ISSUE TITLE
Serialization issues

### ISSUE THREAD

**Issue by alfonsogarciacaro** [elmish/debugger#25]
I'm getting many errors recently when Thoth.Json auto serialization is not capable of serializing the model. We should:

- Improve the error message: at first I always think this is a REST issue.
- Allow passing extra coders to the debugger
- Fall graciously
- Use more relaxed serialization?

I'll try to send a PR :)

**Comment by et1975** [comment]
I think that maybe "extra coders" should instead be "optional encoder/decoder", that way we don't constrain the user in how it's all put together.

**Comment by alfonsogarciacaro** [comment]
Fixed (hopefully) by #26

**Comment by rfrerebe** [comment]
Hello,

I was still having an issue with debugger activated using 3.0.0.
I only had custom encoders and decoders using Thoth, but I was not using [caching](https://mangelmaxime.github.io/Thoth/json/v3.html#caching) because none of my types where auto generated.
I solved it by using [extra coders](https://mangelmaxime.github.io/Thoth/json/v3.html#extra-coders)
and caching.

I can confirm I can **again** use debugger with 3.0.0
